"use strict";
exports.__esModule = true;
var dog_1 = require("./dog");
var cat_1 = require("./cat");
var horse_1 = require("./horse");
var vet_1 = require("./vet");
var dog = new dog_1.Dog("корм", "дома", "Cобака");
dog.sleep();
dog.eat();
dog.makeNoise();
var cat = new cat_1.Cat("мясо", "на столе", "Кот");
cat.sleep();
cat.eat();
cat.makeNoise();
var horse = new horse_1.Horse("овёс", "в загоне", "Лошадь");
horse.sleep();
horse.eat();
horse.makeNoise();
var vet = new vet_1.Vet();
vet.treatAnimal(dog);
vet.treatAnimal(cat);
vet.treatAnimal(horse);
var animals = [];
animals.push(dog.view);
animals.push(cat.view);
animals.push(horse.view);
animals.forEach(function (item) {
    console.log(item);
});
